/* tslint:disable */
/* eslint-disable */
/**
 * agent/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const AgentSortOrder = {
    Desc: 'DESC',
    Asc: 'ASC'
} as const;
export type AgentSortOrder = typeof AgentSortOrder[keyof typeof AgentSortOrder];


export function AgentSortOrderFromJSON(json: any): AgentSortOrder {
    return AgentSortOrderFromJSONTyped(json, false);
}

export function AgentSortOrderFromJSONTyped(json: any, ignoreDiscriminator: boolean): AgentSortOrder {
    return json as AgentSortOrder;
}

export function AgentSortOrderToJSON(value?: AgentSortOrder | null): any {
    return value as any;
}

