/* tslint:disable */
/* eslint-disable */
/**
 * agent/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface AgentUpdatePayload
 */
export interface AgentUpdatePayload {
    /**
     * 
     * @type {string}
     * @memberof AgentUpdatePayload
     */
    'firstname'?: string;
    /**
     * 
     * @type {string}
     * @memberof AgentUpdatePayload
     */
    'lastname'?: string;
    /**
     * 
     * @type {string}
     * @memberof AgentUpdatePayload
     */
    'email'?: string;
    /**
     * 
     * @type {string}
     * @memberof AgentUpdatePayload
     */
    'phone'?: string;
}
