/* tslint:disable */
/* eslint-disable */
/**
 * agent/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface AgentUpdateAgentRequest
 */
export interface AgentUpdateAgentRequest {
    /**
     * 
     * @type {AgentUpdatePayload}
     * @memberof AgentUpdateAgentRequest
     */
    'payload'?: AgentUpdatePayload;
    /**
     * 
     * @type {string}
     * @memberof AgentUpdateAgentRequest
     */
    'payloadMask'?: string;
}
