/* tslint:disable */
/* eslint-disable */
/**
 * agent/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface ListRequestSort
 */
export interface ListRequestSort {
    /**
     * 
     * @type {number}
     * @memberof ListRequestSort
     */
    'evaluationOrder'?: number;
    /**
     * 
     * @type {SortSortField}
     * @memberof ListRequestSort
     */
    'field'?: SortSortField;
    /**
     * 
     * @type {AgentSortOrder}
     * @memberof ListRequestSort
     */
    'order'?: AgentSortOrder;
}
