/* tslint:disable */
/* eslint-disable */
/**
 * agent/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface ListRequestFilters
 */
export interface ListRequestFilters {
    /**
     * 
     * @type {Array<string>}
     * @memberof ListRequestFilters
     */
    'email'?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ListRequestFilters
     */
    'lastname'?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ListRequestFilters
     */
    'code'?: Array<string>;
}
