/**
 * agent/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AgentUpdatePayload } from '../models/AgentUpdatePayload';
import { HttpFile } from '../http/http';

export class AgentUpdateAgentRequest {
    'payload'?: AgentUpdatePayload;
    'payloadMask'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "payload",
            "baseName": "payload",
            "type": "AgentUpdatePayload",
            "format": ""
        },
        {
            "name": "payloadMask",
            "baseName": "payloadMask",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AgentUpdateAgentRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

