/**
 * agent/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ListRequestFilters } from '../models/ListRequestFilters';
import { ListRequestSort } from '../models/ListRequestSort';
import { HttpFile } from '../http/http';

export class AgentListAgentsRequest {
    'pageToken'?: string;
    'sorts'?: Array<ListRequestSort>;
    'filtersMask'?: string;
    'filters'?: ListRequestFilters;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "pageToken",
            "baseName": "pageToken",
            "type": "string",
            "format": ""
        },
        {
            "name": "sorts",
            "baseName": "sorts",
            "type": "Array<ListRequestSort>",
            "format": ""
        },
        {
            "name": "filtersMask",
            "baseName": "filtersMask",
            "type": "string",
            "format": ""
        },
        {
            "name": "filters",
            "baseName": "filters",
            "type": "ListRequestFilters",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AgentListAgentsRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

