/**
 * agent/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AgentAgentEntity } from '../models/AgentAgentEntity';
import { HttpFile } from '../http/http';

export class AgentListResponse {
    'agents'?: Array<AgentAgentEntity>;
    'pageToken'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "agents",
            "baseName": "agents",
            "type": "Array<AgentAgentEntity>",
            "format": ""
        },
        {
            "name": "pageToken",
            "baseName": "pageToken",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AgentListResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

