/**
 * agent/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ListRequestFilters {
    'email'?: Array<string>;
    'lastname'?: Array<string>;
    'code'?: Array<string>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "email",
            "baseName": "email",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "lastname",
            "baseName": "lastname",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "code",
            "baseName": "code",
            "type": "Array<string>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ListRequestFilters.attributeTypeMap;
    }

    public constructor() {
    }
}

