/**
 * agent/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AgentSortOrder } from '../models/AgentSortOrder';
import { SortSortField } from '../models/SortSortField';
import { HttpFile } from '../http/http';

export class ListRequestSort {
    'evaluationOrder'?: number;
    'field'?: SortSortField;
    'order'?: AgentSortOrder;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "evaluationOrder",
            "baseName": "evaluationOrder",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "field",
            "baseName": "field",
            "type": "SortSortField",
            "format": ""
        },
        {
            "name": "order",
            "baseName": "order",
            "type": "AgentSortOrder",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ListRequestSort.attributeTypeMap;
    }

    public constructor() {
    }
}



